server:
  address: 0.0.0.0
  port: 38082
  compression:
    enabled: true
    mime-types: application/json
  servlet:
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tin_info?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type: trace
        enable_lazy_load_no_trans: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

logging:
  file:
    path: log
    name: log/log.log
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    uz:
      ishining:
        didox:
          tin_info: DEBUG
tax:
  url: https://gw.goodsign.biz
